### ISSUE TITLE
arc_select fails on large dataset

### ISSUE THREAD

**Issue by ryanzomorrodi** [R-ArcGIS/arcgislayers#203]
**Describe the bug**
`arc_select()` crashes when downloading a large dataset. Not sure if this is truly connected to it being large or some other aspect of the data, but I can confirm that I am able to download other, smaller datasets.

**To Reproduce**
Use `arc_open` to open a feature service and `arc_select` to download the feature service and return it as an sf.
``` r
library(magrittr)
library(arcgis)

options(RUST_BACKTRACE=1)

PRCP_pred <- "https://services.arcgis.com/GL0fWlNkwysZaKeV/arcgis/rest/services/TXLA_ZCTA_PRCPpred/FeatureServer/0" %>%
    arc_open() %>%
    arc_select()
#> thread '<unnamed>' panicked at arcpbf\src\parse.rs:11:22:
#> internal error: entered unreachable code
#> thread '<unnamed>' panicked at arcpbf\src\lib.rs:156:1:
#> explicit panic
#> Error in multi_resp_process_(resps) :
#>   User function panicked: multi_resp_process_
```
I made the feature service public so you should be able to try to download it for yourself

**Expected behavior**
I expected the feature to be downloaded and stored as an sf. Annoyingly, the error only happens after it seems to have downloaded the entire feature. 

**Additional context**
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64

**Comment by JosiahParry** [comment]
Well here is the good news. I can reproduce the bug with only one feature! Bad news, there's a bug 😲. I'm sorry about that. I'll work on it.
